<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Rosheta.Core.csproj" />
    <Compile Include="..\..\Infrastructure\Data\ApplicationDbContext.cs" Link="Infrastructure\Data\ApplicationDbContext.cs" />
    <Compile Include="..\..\Infrastructure\Data\Repositories\RepositoryBase.cs" Link="Infrastructure\Data\Repositories\RepositoryBase.cs" />
    <Compile Include="..\..\Infrastructure\Data\Repositories\PrescriptionRepository.cs" Link="Infrastructure\Data\Repositories\PrescriptionRepository.cs" />
    <Compile Include="..\..\Infrastructure\Data\UnitOfWork.cs" Link="Infrastructure\Data\UnitOfWork.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Data.Sqlite">
      <HintPath>..\..\Presentation\bin\Debug\net9.0\Microsoft.Data.Sqlite.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>..\..\Presentation\bin\Debug\net9.0\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Abstractions">
      <HintPath>..\..\Presentation\bin\Debug\net9.0\Microsoft.EntityFrameworkCore.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Relational">
      <HintPath>..\..\Presentation\bin\Debug\net9.0\Microsoft.EntityFrameworkCore.Relational.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Sqlite">
      <HintPath>..\..\Presentation\bin\Debug\net9.0\Microsoft.EntityFrameworkCore.Sqlite.dll</HintPath>
    </Reference>
    <Reference Include="SQLitePCLRaw.batteries_v2">
      <HintPath>..\..\Presentation\bin\Debug\net9.0\SQLitePCLRaw.batteries_v2.dll</HintPath>
    </Reference>
    <Reference Include="SQLitePCLRaw.core">
      <HintPath>..\..\Presentation\bin\Debug\net9.0\SQLitePCLRaw.core.dll</HintPath>
    </Reference>
    <Reference Include="SQLitePCLRaw.provider.e_sqlite3">
      <HintPath>..\..\Presentation\bin\Debug\net9.0\SQLitePCLRaw.provider.e_sqlite3.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
